use image::RgbImage;
use clap::{Parser, ArgGroup};

#[derive(Parser)]
#[command(group(
    ArgGroup::new("xor_encryption")
        .required(false)
        .args(["xor_byte"])
))]
#[command(group(
    ArgGroup::new("random_xor")
        .required(false)
        .args(["xor_random", "output_key"])
))]

struct Args {
    filename: String,

    #[arg(short='b', long, help_heading="Encryption modes", help = "XOR with given byte (0-255)", conflicts_with_all = ["xor_random","xor_key"])]
    xor_byte: Option<u8>,
    #[arg(short='r', long, help_heading="Encryption modes", help = "XOR with generated random byte which will be provided in separate file", conflicts_with("xor_byte"))]
    xor_random: bool,
    #[arg(short='o', long, help = "Output key name generated by flag --xor-random")]
    output_key: Option<String>,
    #[arg(short='k', long, value_name="KEY_FILE", help_heading="Encryption modes", help = "Use existing key file")]
    xor_key: Option<String>,
    #[arg(short='p', long, value_name="PASSWORD",help_heading="Encryption modes", help = "XOR with generated by RC4 stream with given password", conflicts_with_all = ["xor_byte","xor_random","xor_key"])]
    xor_rc4_password: Option<String>,

}

fn main() {
    let args = Args::parse();
    let mut img: RgbImage = image::open(&args.filename)
        .unwrap()
        .into_rgb8();
    for pixel in img.pixels_mut() {
        pixel.0 = [
            0xFE ^ pixel[0],
            0xFE ^ pixel[1],
            0xFE ^ pixel[2],
        ];
    }
    img.save("output.png").unwrap();
}
